model:
  audio_encoder:
    type: facebook/hubert-large-ls960-ft
    downsample_method: pool  
    # downsample_factor: 4
    pooling:
      kernel_size: 8
      stride: 4
  llm_embedding_channels: 3072 # GeneZC/MiniChat-2-3B   LLM input embedding size
audio:
  sampling_rate: 16000
train:
  num_gpus: 1
  num_workers: 4
  optimizer:
    lr: 5e-5
    beta1: 0.9
    beta2: 0.999
  batch_size: 1
  grad_accum_interval: 16
  epochs: 20
log:
  checkpoint_dir: checkpoints
  log_dir: logs
  log_interval: 10
  validation_interval: 30000