model:
  audio_encoder:
    type: facebook/hubert-large-ls960-ft
    # downsample_method: pool  
    # downsample_factor: 4
    pooling:
      kernel_size: 8
      stride: 4
  llm_embedding_channels: 3072 # GeneZC/MiniChat-2-3B   LLM input embedding size
audio:
  sampling_rate: 16000
